print('Python Log in test.py')
raise Exception('Error in Python!')